SECRET_TOKEN: 'secret_KEY_goes_HERE'
EMAIL_KEY: 'secrey_KEY_goes_HERE'
EMAIL_SALT: 'secrey_KEY_goes_HERE'
MESSAGE_KEY: 'secret_KEY_goes_HERE'
# For deploying
GIT_REPO: 'git-repo-to-pull-from-remotely.git'
SSH_KEY_DIR: 'local\uri\pointing\to\private\key\with\access\to\server'
# For S3 and deploying
AWS_ACCESS_KEY_ID: 'access_key'
AWS_SECRET_ACCESS_KEY: 'secret_access_key'
AWS_REGION: 'us-east-1'
# For S3 access
S3_BUCKET_NAME: &bucket 'bucket_name'
FOG_DIRECTORY: *bucket
FOG_PROVIDER: 'AWS'
ASSET_HOST: 'cdn.address.goeshere'
production: 
  REDIS_CACHE_ADDRESS: 'redis://:password@hostname:6379/0/cache'
  REDIS_SESSION_ADDRESS: 'redis://:password@hostname:6379/1/sessions'
  REDIS_CABLE_ADDRESS: 'redis//:password@hostname:6379/2/cables'
  SMTP_ADDRESS:  'smtp-host.address-goes.here'
  SMTP_PORT:     '587'
  SMTP_USERNAME: 'smtp_username'
  SMTP_PASSWORD: 'smtp_password'