SECRET_TOKEN: 'secret_KEY_goes_HERE'
EMAIL_KEY: 'secrey_KEY_goes_HERE'
EMAIL_SALT: 'secrey_KEY_goes_HERE'
S3_BUCKET_NAME: &bucket 'bucket_name'
AWS_ACCESS_KEY_ID: 'access_key'
AWS_SECRET_ACCESS_KEY: 'secret_access_key'
FOG_DIRECTORY: *bucket
FOG_PROVIDER: 'AWS'
production: 
  REDIS_CACHE_ADDRESS: 'redis://:password@hostname:6379/0/cache'
  REDIS_SESSION_ADDRESS: 'redis://:password@hostname:6379/1/sessions'