development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_ADDRESS") %>
  channel_prefix: league_for_gamers_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_ADDRESS") %>
  channel_prefix: league_for_gamers_production
